### ISSUE TITLE
Feature: allow partition/cluster config on bigquery mvs

### ISSUE THREAD

**Issue by makermary** [dbt-labs/dbt-labs-experimental-features#28]
We can pass partition/cluster config fields to tables in bigquery thanks to the dbt-bigquery core codebase. We would like to be able to do the same for materialized views.

#27 adds the functionality to allow this to happen.

Thanks!

**Comment by dataders** [comment]
partition and cluster configs are supported in the official implementation of Big Query materialized views -- see [dbt docs: Big Query configurations: materialized views](https://docs.getdbt.com/reference/resource-configs/bigquery-configs#materialized-views)

Materialized Views have been supported in dbt since dbt-core 1.7 (November 2023). See [dbt docs: materialized views](https://docs.getdbt.com/docs/build/materializations#materialized-view) for more information.

The version of materialized views in this experimental repo is is long-overdue for official deprecation -- it has not been meaningfully maintained or improved for over three years (see https://github.com/dbt-labs/dbt-labs-experimental-features/pull/11).

If you haven't already, you should try out the official implementation! Should you encounter an issue, you can then open bug or enhancement ticket on either dbt-core or the dbt-bigquery for your current data platform.
